full:
  image: startx/sxapi:latest
  container_name: "sxapi-simple-full"
  cpu_shares: 4096
  mem_limit: 1g
  memswap_limit: 1g
  restart: "on-failure:2"
  privileged: true
  ports:
    - "8080:19777"
  volumes:
    - "~/sxapi-data:/data"
    - "./:/conf"